version: '3.8'
services:
  dev-db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    volumes:
      - ./db/data:/var/lib/postgresql/data
